id: PBE6643E3
initial_creation_type: ocr
source_metadata:
  volumes:
    42aaa802256447e6a0c14a20452ecc03:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: རྡོ་རྗེ་བྱབ་པའི་ལས་ཚོགས།
      total_pages: 1379
      volume_number: 37
